/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vending.machine;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import java.util.TimerTask;
import javax.imageio.ImageIO;
import javax.imageio.stream.FileImageOutputStream;
import javax.swing.*;

/**
 *
 * @author Khukuh
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
            listMakanan = Makanan.getMakanan();
            initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_makanan = new javax.swing.JPanel();
        panel_mkn_1 = new javax.swing.JPanel();
        lbl_mkn_1 = new javax.swing.JLabel();
        lbl_harga_1 = new javax.swing.JLabel();
        lbl_stok_1 = new javax.swing.JLabel();
        lbl_gambar_1 = new javax.swing.JLabel();
        panel_mkn_2 = new javax.swing.JPanel();
        lbl_mkn_2 = new javax.swing.JLabel();
        lbl_harga_2 = new javax.swing.JLabel();
        lbl_stok_2 = new javax.swing.JLabel();
        lbl_gambar_2 = new javax.swing.JLabel();
        panel_mkn_3 = new javax.swing.JPanel();
        lbl_mkn_3 = new javax.swing.JLabel();
        lbl_harga_3 = new javax.swing.JLabel();
        lbl_stok_3 = new javax.swing.JLabel();
        lbl_gambar_3 = new javax.swing.JLabel();
        panel_mkn_4 = new javax.swing.JPanel();
        lbl_mkn_4 = new javax.swing.JLabel();
        lbl_harga_4 = new javax.swing.JLabel();
        lbl_stok_4 = new javax.swing.JLabel();
        lbl_gambar_4 = new javax.swing.JLabel();
        panel_mkn_5 = new javax.swing.JPanel();
        lbl_mkn_5 = new javax.swing.JLabel();
        lbl_harga_5 = new javax.swing.JLabel();
        lbl_stok_5 = new javax.swing.JLabel();
        lbl_gambar_5 = new javax.swing.JLabel();
        panel_input = new javax.swing.JPanel();
        tf_input = new javax.swing.JTextField();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();
        tf_input_uang = new javax.swing.JTextField();
        lbl_input_uang = new javax.swing.JLabel();
        btn_input_uang = new javax.swing.JButton();
        label_uang = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        panel_kembalian = new javax.swing.JPanel();
        btn_ambil = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel_kembalian2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panel_makanan_pilihan = new javax.swing.JPanel();
        lbl_kembalian = new javax.swing.JLabel();
        lbl_uang_kembalian = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SnackMachine v0.1");
        setResizable(false);

        panel_makanan.setBackground(new java.awt.Color(153, 153, 255));

        lbl_mkn_1.setText("001 - "+listMakanan.get(0).nama);

        lbl_harga_1.setText(""+listMakanan.get(0).harga);

        lbl_stok_1.setText(listMakanan.get(0).stok+" buah");

        lbl_gambar_1.setToolTipText("");
        try{
            java.awt.Dimension newSize = new java.awt.Dimension(107, 72);
            lbl_gambar_1.setIcon(new javax.swing.ImageIcon(
                Utils.resizeImage(
                    javax.imageio.ImageIO.read(
                        getClass().getResource("/images/biskies.png")), newSize)));
    }catch(Exception e){
        System.out.println("Error: "+e.getMessage());
    }

    javax.swing.GroupLayout panel_mkn_1Layout = new javax.swing.GroupLayout(panel_mkn_1);
    panel_mkn_1.setLayout(panel_mkn_1Layout);
    panel_mkn_1Layout.setHorizontalGroup(
        panel_mkn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_mkn_1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_mkn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_mkn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_mkn_1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lbl_harga_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_stok_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(lbl_gambar_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(7, Short.MAX_VALUE))
    );
    panel_mkn_1Layout.setVerticalGroup(
        panel_mkn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mkn_1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl_gambar_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_mkn_1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_harga_1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_stok_1)
            .addGap(16, 16, 16))
    );

    lbl_mkn_2.setText("002 - "+listMakanan.get(1).nama);

    lbl_harga_2.setText(""+listMakanan.get(1).harga);

    lbl_stok_2.setText(listMakanan.get(1).stok+" buah");

    try{
        java.awt.Dimension newSize = new java.awt.Dimension(107, 72);
        lbl_gambar_2.setIcon(new javax.swing.ImageIcon(
            Utils.resizeImage(
                javax.imageio.ImageIO.read(
                    getClass().getResource("/images/bengbeng.png")), newSize)));
    }catch(Exception e){
        System.out.println("Error: "+e.getMessage());
    }

    javax.swing.GroupLayout panel_mkn_2Layout = new javax.swing.GroupLayout(panel_mkn_2);
    panel_mkn_2.setLayout(panel_mkn_2Layout);
    panel_mkn_2Layout.setHorizontalGroup(
        panel_mkn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_mkn_2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_mkn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_gambar_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_mkn_2Layout.createSequentialGroup()
                    .addGroup(panel_mkn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_mkn_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(lbl_harga_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_stok_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 17, Short.MAX_VALUE)))
            .addContainerGap())
    );
    panel_mkn_2Layout.setVerticalGroup(
        panel_mkn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mkn_2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl_gambar_2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_mkn_2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_harga_2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_stok_2)
            .addGap(16, 16, 16))
    );

    lbl_mkn_3.setText("003 - "+listMakanan.get(2).nama);

    lbl_harga_3.setText(""+listMakanan.get(2).harga);

    lbl_stok_3.setText(listMakanan.get(2).stok+" buah");

    try{
        java.awt.Dimension newSize = new java.awt.Dimension(107, 72);
        lbl_gambar_3.setIcon(new javax.swing.ImageIcon(
            Utils.resizeImage(
                javax.imageio.ImageIO.read(
                    getClass().getResource("/images/chitato.png")), newSize)));
    }catch(Exception e){
        System.out.println("Error: "+e.getMessage());
    }

    javax.swing.GroupLayout panel_mkn_3Layout = new javax.swing.GroupLayout(panel_mkn_3);
    panel_mkn_3.setLayout(panel_mkn_3Layout);
    panel_mkn_3Layout.setHorizontalGroup(
        panel_mkn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_mkn_3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_mkn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_mkn_3Layout.createSequentialGroup()
                    .addGroup(panel_mkn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_mkn_3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(lbl_harga_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_stok_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 18, Short.MAX_VALUE))
                .addComponent(lbl_gambar_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    panel_mkn_3Layout.setVerticalGroup(
        panel_mkn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mkn_3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl_gambar_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_mkn_3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_harga_3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_stok_3)
            .addGap(16, 16, 16))
    );

    lbl_mkn_4.setText("004 - "+listMakanan.get(3).nama);

    lbl_harga_4.setText(""+listMakanan.get(3).harga);

    lbl_stok_4.setText(listMakanan.get(3).stok+" buah");

    try{
        java.awt.Dimension newSize = new java.awt.Dimension(107, 72);
        lbl_gambar_4.setIcon(new javax.swing.ImageIcon(
            Utils.resizeImage(
                javax.imageio.ImageIO.read(
                    getClass().getResource("/images/lays.png")), newSize)));
    }catch(Exception e){
        System.out.println("Error: "+e.getMessage());
    }

    javax.swing.GroupLayout panel_mkn_4Layout = new javax.swing.GroupLayout(panel_mkn_4);
    panel_mkn_4.setLayout(panel_mkn_4Layout);
    panel_mkn_4Layout.setHorizontalGroup(
        panel_mkn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_mkn_4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_mkn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_mkn_4Layout.createSequentialGroup()
                    .addGroup(panel_mkn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_mkn_4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(lbl_harga_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_stok_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 18, Short.MAX_VALUE))
                .addComponent(lbl_gambar_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    panel_mkn_4Layout.setVerticalGroup(
        panel_mkn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mkn_4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl_gambar_4, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_mkn_4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_harga_4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_stok_4)
            .addGap(16, 16, 16))
    );

    lbl_mkn_5.setText("005 - "+listMakanan.get(4).nama);

    lbl_harga_5.setText(""+listMakanan.get(4).harga);

    lbl_stok_5.setText(listMakanan.get(4).stok+" buah");

    try{
        java.awt.Dimension newSize = new java.awt.Dimension(107, 72);
        lbl_gambar_5.setIcon(new javax.swing.ImageIcon(
            Utils.resizeImage(
                javax.imageio.ImageIO.read(
                    getClass().getResource("/images/oreo.png")), newSize)));
    }catch(Exception e){
        System.out.println("Error: "+e.getMessage());
    }

    javax.swing.GroupLayout panel_mkn_5Layout = new javax.swing.GroupLayout(panel_mkn_5);
    panel_mkn_5.setLayout(panel_mkn_5Layout);
    panel_mkn_5Layout.setHorizontalGroup(
        panel_mkn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_mkn_5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_mkn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_mkn_5Layout.createSequentialGroup()
                    .addGroup(panel_mkn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_mkn_5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(lbl_harga_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_stok_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 18, Short.MAX_VALUE))
                .addComponent(lbl_gambar_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    panel_mkn_5Layout.setVerticalGroup(
        panel_mkn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mkn_5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl_gambar_5, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_mkn_5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_harga_5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_stok_5)
            .addGap(16, 16, 16))
    );

    javax.swing.GroupLayout panel_makananLayout = new javax.swing.GroupLayout(panel_makanan);
    panel_makanan.setLayout(panel_makananLayout);
    panel_makananLayout.setHorizontalGroup(
        panel_makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_makananLayout.createSequentialGroup()
            .addContainerGap(47, Short.MAX_VALUE)
            .addGroup(panel_makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_makananLayout.createSequentialGroup()
                    .addComponent(panel_mkn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(panel_mkn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_makananLayout.createSequentialGroup()
                    .addComponent(panel_mkn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(panel_mkn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(panel_mkn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(35, 35, 35))
    );
    panel_makananLayout.setVerticalGroup(
        panel_makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_makananLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(panel_mkn_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_mkn_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_mkn_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panel_makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(panel_mkn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panel_mkn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(117, 117, 117))
    );

    panel_input.setBackground(new java.awt.Color(255, 153, 153));

    tf_input.setEditable(false);

    btn_1.setText("1");
    btn_1.setPreferredSize(new java.awt.Dimension(30, 30));
    btn_1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_1ActionPerformed(evt);
        }
    });

    btn_2.setText("2");
    btn_2.setPreferredSize(new java.awt.Dimension(30, 30));
    btn_2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_2ActionPerformed(evt);
        }
    });

    btn_3.setText("3");
    btn_3.setPreferredSize(new java.awt.Dimension(30, 30));
    btn_3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_3ActionPerformed(evt);
        }
    });

    btn_4.setText("4");
    btn_4.setPreferredSize(new java.awt.Dimension(30, 30));
    btn_4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_4ActionPerformed(evt);
        }
    });

    btn_5.setText("5");
    btn_5.setPreferredSize(new java.awt.Dimension(30, 30));
    btn_5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_5ActionPerformed(evt);
        }
    });

    btn_6.setText("6");
    btn_6.setPreferredSize(new java.awt.Dimension(30, 30));
    btn_6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_6ActionPerformed(evt);
        }
    });

    btn_7.setText("7");
    btn_7.setPreferredSize(new java.awt.Dimension(30, 30));
    btn_7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_7ActionPerformed(evt);
        }
    });

    btn_8.setText("8");
    btn_8.setPreferredSize(new java.awt.Dimension(30, 30));
    btn_8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_8ActionPerformed(evt);
        }
    });

    btn_9.setText("9");
    btn_9.setPreferredSize(new java.awt.Dimension(30, 30));
    btn_9.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_9ActionPerformed(evt);
        }
    });

    btn_0.setText("0");
    btn_0.setPreferredSize(new java.awt.Dimension(30, 30));
    btn_0.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_0ActionPerformed(evt);
        }
    });

    btn_clear.setText("CLEAR");
    btn_clear.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_clearActionPerformed(evt);
        }
    });

    btn_ok.setText("OK");
    btn_ok.setPreferredSize(new java.awt.Dimension(30, 30));
    btn_ok.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_okActionPerformed(evt);
        }
    });

    javax.swing.text.PlainDocument doc = (javax.swing.text.PlainDocument) tf_input_uang.getDocument();
    doc.setDocumentFilter(new vending.machine.MyIntFilter());

    lbl_input_uang.setText("Uang :");

    btn_input_uang.setText("ENTER");
    btn_input_uang.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_input_uangActionPerformed(evt);
        }
    });

    label_uang.setText("0");

    btn_reset.setText("RESET");
    btn_reset.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_resetActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout panel_inputLayout = new javax.swing.GroupLayout(panel_input);
    panel_input.setLayout(panel_inputLayout);
    panel_inputLayout.setHorizontalGroup(
        panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_inputLayout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_inputLayout.createSequentialGroup()
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_inputLayout.createSequentialGroup()
                            .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_input_uang, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_inputLayout.createSequentialGroup()
                                .addComponent(lbl_input_uang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_uang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btn_input_uang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_inputLayout.createSequentialGroup()
                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_inputLayout.createSequentialGroup()
                            .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createSequentialGroup()
                            .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_ok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
        .addGroup(panel_inputLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(tf_input, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(23, 23, 23))
    );
    panel_inputLayout.setVerticalGroup(
        panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tf_input, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_reset))
            .addGap(18, 18, 18)
            .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(29, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_input_uang)
                .addComponent(label_uang))
            .addGap(7, 7, 7)
            .addComponent(tf_input_uang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_input_uang)
            .addContainerGap())
    );

    panel_kembalian.setBackground(new java.awt.Color(153, 255, 153));

    btn_ambil.setText("Ambil");
    btn_ambil.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_ambilActionPerformed(evt);
        }
    });

    panel_kembalian2.setForeground(new java.awt.Color(255, 255, 255));
    panel_kembalian2.setLayout(new java.awt.FlowLayout());
    panel_kembalian2.setComponentOrientation(java.awt.ComponentOrientation.LEFT_TO_RIGHT);
    jScrollPane2.setViewportView(panel_kembalian2);

    panel_makanan_pilihan.setForeground(new java.awt.Color(255, 255, 255));
    jScrollPane3.setViewportView(panel_makanan_pilihan);

    lbl_kembalian.setText("Kembalian:");

    javax.swing.GroupLayout panel_kembalianLayout = new javax.swing.GroupLayout(panel_kembalian);
    panel_kembalian.setLayout(panel_kembalianLayout);
    panel_kembalianLayout.setHorizontalGroup(
        panel_kembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_kembalianLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_kembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_kembalianLayout.createSequentialGroup()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_ambil, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(panel_kembalianLayout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panel_kembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_kembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_uang_kembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap())
    );
    panel_kembalianLayout.setVerticalGroup(
        panel_kembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_kembalianLayout.createSequentialGroup()
            .addGroup(panel_kembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_kembalianLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_kembalian)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbl_uang_kembalian)
                    .addGap(61, 61, 61))
                .addGroup(panel_kembalianLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
            .addGroup(panel_kembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_kembalianLayout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(btn_ambil)
                    .addGap(41, 41, 41))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_kembalianLayout.createSequentialGroup()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())))
    );

    jLabel1.setText("SELAMAT DATANG DI VENDING MACHINE V0.1");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_makanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(panel_kembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panel_makanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panel_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panel_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        tf_input.setText(tf_input.getText()+"9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        tf_input.setText(tf_input.getText()+"1");
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        tf_input.setText(tf_input.getText()+"2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        tf_input.setText(tf_input.getText()+"3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        tf_input.setText(tf_input.getText()+"4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        tf_input.setText(tf_input.getText()+"5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        tf_input.setText(tf_input.getText()+"6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        tf_input.setText(tf_input.getText()+"7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        tf_input.setText(tf_input.getText()+"8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        tf_input.setText(tf_input.getText()+"0");
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        tf_input.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        boolean valid = false;
        String message = "";
        switch(status){
            case -1:
                message = "Anda belum memasukkan uang!";
                tf_input.setText("");
                break;
            case 0:
                valid = true;
                break;
            case 1:
                message = "Silahkan diambil makanannya!";
                break;
        }
        if(!valid){
            JOptionPane.showMessageDialog(null, message);
            return;
        }
        if(tf_input.getText().equals("") && input_uang == 0){
            JOptionPane.showMessageDialog(null, "Input tidak boleh kosong");
            return;
        }
        input_kode = tf_input.getText().trim();
        tf_input.setText("");
        boolean found = false;
        Makanan pilihanMakanan = new Makanan("", "", 0,0, "");
        for(Makanan makanan: listMakanan){
            if(makanan.kode.equals(input_kode)){
                pilihanMakanan = makanan;
                found = true;
                break;
            }
        }
        if(!found){
            JOptionPane.showMessageDialog(null, "Produk tidak ditemukan, silahkan input lagi");
            return;
        }
        if(input_uang - pilihanMakanan.harga < 0){
            JOptionPane.showMessageDialog(null, "Uang tidak mencukupi!");
            return;
        }
        if(pilihanMakanan.stok <= 0){
            JOptionPane.showMessageDialog(null, "Stok makanan yang dipilih habis!");
            return;
        }
        pilihanMakanan.changeStock(-1);
        lbl_stok_1.setText(listMakanan.get(0).stok+" buah");
        lbl_stok_2.setText(listMakanan.get(1).stok+" buah");
        lbl_stok_3.setText(listMakanan.get(2).stok+" buah");
        lbl_stok_4.setText(listMakanan.get(3).stok+" buah");
        lbl_stok_5.setText(listMakanan.get(4).stok+" buah");
        kembalian = Makanan.kembalianUang((input_uang-pilihanMakanan.harga));
        int nilaiKembalian = 0;
        for(Uang uang: kembalian){
            panel_kembalian2.add(Utils.getLabelWithImage(uang.gambar, getClass(), new Dimension(100,100)));
            nilaiKembalian += uang.nilai;
        }
        panel_makanan_pilihan.add(Utils.getLabelWithImage(pilihanMakanan.gambar, getClass(), new Dimension(150,150)));
        input_uang = 0;
        label_uang.setText("");
        lbl_uang_kembalian.setText("Rp. "+nilaiKembalian);
        JOptionPane.showMessageDialog(null, "Produk "+pilihanMakanan.nama+" telah dipilih. Silahkan diambil");
        status++;
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_input_uangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_input_uangActionPerformed
        boolean valid = false;
        String message = "";
        switch(status){
            case -1:
                valid = true;
                break;
            case 0:
                message = "Anda sudah memasukkan uang!";
                break;
            case 1:
                message = "Silahkan diambil makanannya!";
                break;
            default:
                message = "Mohon ulang";
        }
        if(!valid){
            JOptionPane.showMessageDialog(null, message);
            return;
        }
        input_uang = Integer.parseInt(tf_input_uang.getText().trim());
        if(tf_input_uang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukkan nilai uang");
            return;
        }
        input_uang = Integer.parseInt(tf_input_uang.getText().trim());
        if(input_uang > 20000){
            JOptionPane.showMessageDialog(null, "Uang tidak boleh melebihi Rp. 20.000");
            return;
        }
        if(Makanan.kembalianUang(input_uang).isEmpty()){
            JOptionPane.showMessageDialog(null, "Uang tidak ada pecahannya");
            return;
        }
        tf_input_uang.setText("");
        label_uang.setText(""+input_uang);
        status++;
    }//GEN-LAST:event_btn_input_uangActionPerformed

    private void btn_ambilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ambilActionPerformed
        boolean valid = false;
        String message = "";
        switch(status){
            case -1:
                message = "Masukkan uang terlebih dahulu";
                break;
            case 0:
                message = "Silahkan ambil makanan";
                break;
            case 1:
                valid = true;
                break;
        }
        if(!valid){
            JOptionPane.showMessageDialog(null, message);
            return;
        }
        kembalian.clear();
        panel_kembalian2.removeAll();
        panel_makanan_pilihan.removeAll();
        panel_kembalian2.repaint();
        panel_makanan_pilihan.repaint();
        status = -1;
    }//GEN-LAST:event_btn_ambilActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        input_kode = "";
        input_uang = 0;
        status = -1;
        listMakanan = Makanan.getMakanan();
        kembalian.clear();
        panel_kembalian2.removeAll();
        panel_makanan_pilihan.removeAll();
        panel_kembalian2.repaint();
        panel_makanan_pilihan.repaint();
        lbl_stok_1.setText(""+listMakanan.get(0).stok);
        lbl_stok_2.setText(""+listMakanan.get(1).stok);
        lbl_stok_3.setText(""+listMakanan.get(2).stok);
        lbl_stok_4.setText(""+listMakanan.get(3).stok);
        lbl_stok_5.setText(""+listMakanan.get(4).stok);
        label_uang.setText("");
        tf_input.setText("");
        tf_input_uang.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public String input_kode = "";
    public ArrayList<Makanan> listMakanan = new ArrayList<>();
    public int input_uang = 0;
    public List<Uang> kembalian = new ArrayList<>();
    public int status = -1; //-1 untuk belum ngapa2in
                            //0 untuk setelah masukkan uang
                            //1 untuk setelah masukkan kode
                            //2 untuk setelah mengambil makanan

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_ambil;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_input_uang;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_uang;
    private javax.swing.JLabel lbl_gambar_1;
    private javax.swing.JLabel lbl_gambar_2;
    private javax.swing.JLabel lbl_gambar_3;
    private javax.swing.JLabel lbl_gambar_4;
    private javax.swing.JLabel lbl_gambar_5;
    private javax.swing.JLabel lbl_harga_1;
    private javax.swing.JLabel lbl_harga_2;
    private javax.swing.JLabel lbl_harga_3;
    private javax.swing.JLabel lbl_harga_4;
    private javax.swing.JLabel lbl_harga_5;
    private javax.swing.JLabel lbl_input_uang;
    private javax.swing.JLabel lbl_kembalian;
    private javax.swing.JLabel lbl_mkn_1;
    private javax.swing.JLabel lbl_mkn_2;
    private javax.swing.JLabel lbl_mkn_3;
    private javax.swing.JLabel lbl_mkn_4;
    private javax.swing.JLabel lbl_mkn_5;
    private javax.swing.JLabel lbl_stok_1;
    private javax.swing.JLabel lbl_stok_2;
    private javax.swing.JLabel lbl_stok_3;
    private javax.swing.JLabel lbl_stok_4;
    private javax.swing.JLabel lbl_stok_5;
    private javax.swing.JLabel lbl_uang_kembalian;
    private javax.swing.JPanel panel_input;
    private javax.swing.JPanel panel_kembalian;
    private javax.swing.JPanel panel_kembalian2;
    private javax.swing.JPanel panel_makanan;
    private javax.swing.JPanel panel_makanan_pilihan;
    private javax.swing.JPanel panel_mkn_1;
    private javax.swing.JPanel panel_mkn_2;
    private javax.swing.JPanel panel_mkn_3;
    private javax.swing.JPanel panel_mkn_4;
    private javax.swing.JPanel panel_mkn_5;
    private javax.swing.JTextField tf_input;
    private javax.swing.JTextField tf_input_uang;
    // End of variables declaration//GEN-END:variables
}
